#!/bin/sh

# Created by Christian Schwarz on 30 Aug 2014.

# PROVIDE: unicorn
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="unicorn"
rcvar="${name}_enable"

load_rc_config "${name}"

#global flags
: ${unicorn_enable:="NO"}
: ${unicorn_children:=""} #e.g.: xyz_children="foo bar" => xyz_foo_variable="" and xyz_bar_variable=""

_children="${unicorn_children}"

# If no specific child is mentioned, apply command to all children
if [ -z "$2" ]; then

        for _child in ${_children}; do
		child_rcvar="${name}_${_child}_enable
		if checkyesno ${child_rcvar}; then
			echo "Running ${1} on ${_child}"
			$0 $1 $_child
		else
			echo "Skipping ${_child}"
		fi
        done
        exit 0
fi
_child="$2"

#Sets the global variable globname fromt he values defined in rc.conf. Enable rc_debug="YES" for detailed logs.
_set_child_var()
{
    globname=$1
    var=$2
    mandatory=$3
    alternative=$4
    varname="unicorn_${_child}_${var}"
    debug "Mapping '${varname}' to script-global '${globname}' (mandatory=${mandatory} default=${alternative})"
    eval value="\${$varname:-${default}}"
    if [ "$mandatory" == "yes" ] && [ -z "$value" ]; then
        err 1 "$varname is mandatory"
        exit 1
    elif [ -n "$value" ]; then
        usedValue="$value"
    elif [ -n "$alternative" ]; then
        usedValue="$alternative"
    else
        err 1 "You have to specify an alternative for $varname"
        exit 1
    fi
    debug "$globname=$usedValue"
    eval "${globname}=\"${usedValue}\""
}

# set the rcvar for this specific child
rcvar="${name}_${_child}_enable"
rcvar="${rcvar}"

#non-rc.d vars
_set_child_var 'unicorn_config' "config" 'yes'
_set_child_var 'rails_env' 'env' 'no' 'production'

#rc.d vars
_set_child_var 'unicorn_chdir' 'directory' 'yes'
_set_child_var 'unicorn_user' 'user' 'yes'
_set_child_var 'unicorn_group' 'group' 'no' "$unicorn_user"
_set_child_var 'pidfile' 'pidfile' 'no' "${unicorn_chdir}/tmp/pids/unicorn.pid"

procname="ruby19" #check bundler's shebang for details
command="/usr/local/bin/bundle"
command_args="exec /usr/local/bin/unicorn -c ${unicorn_config} -E ${rails_env} -D"
sig_stop="QUIT"

required_dirs="${unicorn_chdir}"
required_files="${unicorn_config}"

run_rc_command "${1}"
